### ISSUE TITLE
Please make AUR package & could you take on trafshow

### ISSUE THREAD

**Issue by SCCOBN** [resurrecting-open-source-projects/cbm#3]
Hi. Thank you for maintaining it, just compiled on arch, it's working!

Could you please make an AUR package?

Also, this package, trafshow, needs a maintainer, it does not compile. Some stupid type conversion problem with new C++ standards. Could you take it on? https://aur.archlinux.org/packages/trafshow/

**Comment by daltomi** [comment]
Unfortunately there is already a package, `cbm-git`, that installs the binary with name `cbm` and this would generate collision. I don't know what the AUR policy is in these cases.

Regarding `trafshow`, I sent a link with a patch, you can see it in _Comments_ on the AUR site.

On including `trafshow` to `resurrecting-open-source-projects` this must be decided by @eribertomota  :-)

**Comment by eribertomota** [comment]
Em qui., 25 de fev. de 2021 às 21:15, Daniel T. Borelli <
notifications@github.com> escreveu:

> On including trafshow to resurrecting-open-source-projects this must be
> decided by @eribertomota <https://github.com/eribertomota> :-)
>
>
>
Hi,

For now I don't intend to add trafshow in resurrecting-open-source-projects.

Cheers,

Eriberto
